language: node_js
dist: trusty
node_js:
  - 8
before_install:
  - export DISPLAY=:99.0
install:
  - sh -e /etc/init.d/xvfb start
  - yarn install
script:
  - yarn checkformat --sha1=$TRAVIS_COMMIT --sha2=$(git merge-base HEAD $TRAVIS_BRANCH)
  - yarn test
  - yarn e2e
addons:
  chrome: stable
cache:
  directories:
    - node_modules
notifications:
  email: false
  webhooks:
    on_success: true
    on_failure: true
    on_start: true
