[package]
name = 'nx'
version = '0.1.0'
edition = '2021'

[dependencies]
xxhash-rust = { version = '0.8.5', features = ['xxh3', 'xxh64'] }
napi = { version = '2.10.2', default-features = false, features = ['anyhow', 'napi4', 'tokio_rt'] }
napi-derive = '2.9.3'
ignore = '0.4'
crossbeam-channel = '0.5'

ignore-files = {path = "/Users/jon/Dev/watchexec/crates/ignore-files", version = "1.2.0"}
watchexec = { path = "/Users/jon/Dev/watchexec/crates/lib", version = "2.3.0" }
watchexec-filterer-ignore = {path = "/Users/jon/Dev/watchexec/crates/filterer/ignore", version = "1.2.0"}
watchexec-events = { path = "/Users/jon/Dev/watchexec/crates/events", version = "1.0.0"}
watchexec-signals = { path = "/Users/jon/Dev/watchexec/crates/signals", version = "1.0.0"}

tracing-subscriber = "0.3.17"
anyhow = "1.0.71"
itertools = "0.10.5"

[lib]
crate-type = ['cdylib']

[build-dependencies]
napi-build = '2.0.1'

[dev-dependencies]
assert_fs = "1.0.10"
