name: Unmergable Labels Check

on:
  pull_request:
    types: [synchronize, opened, reopened, labeled, unlabeled]

jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      - run: sudo ln -s /usr/local/lib/node_modules/lerna/node_modules/.bin/nx /usr/local/bin/nx

      - uses: actions/checkout@v3

      - run: nx print-affected
